### PR TITLE
Added empty String check in ToStringTest as that is a new Pitest check.

### PR DESCRIPTION
**Pull request by boothen**
Pitest version 1.4.11 has added a new check around toString returning an empty String. Added in this check.

### CODE REVIEW

**Comment by Derek-Ashmore** [comment]
Thanks for the Pull Request -- we're taking a look and will be back to you shortly

**Comment by boothen** [comment]
Hi @Derek-Ashmore ,

Thanks for picking this up so quickly. Apologies, I meant to raise an issue around this.

Cheers,
Matt.

**Comment by Derek-Ashmore** [comment]
Thank you!   An RC with your change is on its way out.  I'll tag you when it's there.  Nexus isn't the quickest

⁣Get BlueMail for Android ​

**Comment by Derek-Ashmore** [comment]
Hi -- your changes are in release 1.0.1-rc1 -- please take a gander when you get a chance.  If we don't see any issues with it after a week or so, I'll GA it

**Comment by boothen** [comment]
Hi Derek,

Thanks for the quick turnaround. I'll update to the RC version and let you know.

Cheers,
Matt.

**Comment by boothen** [comment]
Hi Derek,

I've updated to use the RC version and can confirm it works as expected.

Cheers,
Matt.

**Pull request merged**
